nix: Update nixpkgs to get updated docker-compose
Without this docker-compose complains about depends_on config settings:

> ERROR: The Compose file './docker-compose.yml' is invalid because:
> services.tink-server.depends_on.generate-tls-certs.condition contains "service_completed_successfully", which is an invalid type, it should be a service_started, or a service_healthy
> services.web-assets-server.depends_on.fetch-and-convert-ubuntu-img.condition contains "service_completed_successfully", which is an invalid type, it should be a service_started, or a service_healthy
> services.registry.depends_on.generate-tls-certs.condition contains "service_completed_successfully", which is an invalid type, it should be a service_started, or a service_healthy

This was due to https://github.com/docker/compose/issues/8154.

Signed-off-by: Manuel Mendez <github@i.m.mmlb.dev>